In [2]:
# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install --user pandas

Collecting pandas
  Using cached pandas-1.5.2-cp38-cp38-win_amd64.whl (11.0 MB)
Requirement already satisfied: pytz>=2020.1 in c:\users\mtriv\appdata\roaming\python\python38\site-packages (from pandas) (2020.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\mtriv\appdata\roaming\python\python38\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in c:\python38\lib\site-packages (from pandas) (1.24.0)
Requirement already satisfied: six>=1.5 in c:\python38\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.15.0)
Installing collected packages: pandas
Successfully installed pandas-1.5.2

WARNING: You are using pip version 20.2.3; however, version 22.3.1 is available.
You should consider upgrading via the 'C:\Python38\python.exe -m pip install --upgrade pip' command.

In [3]:
# View packages in the kernel
pip list

Package                  Version
------------------------ -----------
-                        p
-ip                      20.1.1
aniso8601                8.0.0
anyio                    3.6.2
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
asttokens                2.2.1
attrs                    22.1.0
Babel                    2.11.0
backcall                 0.2.0
beautifulsoup4           4.11.1
bleach                   5.0.1
certifi                  2022.12.7
cffi                     1.15.1
chardet                  3.0.4
charset-normalizer       2.1.1
Click                    7.0
colorama                 0.4.6
comm                     0.1.2
debugpy                  1.6.4
decorator                5.1.1
defusedxml               0.7.1
distlib                  0.3.6
entrypoints              0.4
executing                1.2.0
fastjsonschema           2.16.2
filelock                 3.8.2
Flask                    1.1.1
Flask-RESTful            0.3.8
idna                     3.4
importlib-metadata       5.2.0
importlib-resources      5.10.1
ipykernel                6.19.4
ipython                  8.7.0
ipython-genutils         0.2.0
itsdangerous             1.1.0
jedi                     0.18.2
Jinja2                   2.10.3
json5                    0.9.10
jsonschema               4.17.3
jupyter-client           7.4.8
jupyter-core             5.1.0
jupyter-events           0.5.0
jupyter-server           2.0.2
jupyter-server-terminals 0.4.3
jupyterlab               3.5.2
jupyterlab-pygments      0.2.2
jupyterlab-server        2.16.5
MarkupSafe               1.1.1
matplotlib-inline        0.1.6
mistune                  2.0.4
nbclassic                0.4.8
nbclient                 0.7.2
nbconvert                7.2.7
nbformat                 5.7.1
nest-asyncio             1.5.6
notebook                 6.5.2
notebook-shim            0.2.2
numpy                    1.24.0
packaging                22.0
pandas                   1.5.2
pandocfilters            1.5.0
parso                    0.8.3
pickleshare              0.7.5
pip                      20.2.3
pkgutil-resolve-name     1.3.10
platformdirs             2.6.0
prometheus-client        0.15.0
prompt-toolkit           3.0.36
psutil                   5.9.4
psycopg2-binary          2.8.6
pure-eval                0.2.2
pycparser                2.21
Pygments                 2.13.0
pyrsistent               0.19.2
python-dateutil          2.8.2
python-json-logger       2.0.4
pytz                     2020.1
pywin32                  305
pywinpty                 2.0.9
PyYAML                   6.0
pyzmq                    24.0.1
requests                 2.28.1
Send2Trash               1.8.0
setuptools               47.1.0
six                      1.15.0
sniffio                  1.3.0
soupsieve                2.3.2.post1
stack-data               0.6.2
terminado                0.17.1
tinycss2                 1.2.1
tomli                    2.0.1
tornado                  6.2
traitlets                5.8.0
urllib3                  1.26.13
virtualenv               20.17.1
wcwidth                  0.2.5
webencodings             0.5.1
websocket-client         1.4.2
Werkzeug                 0.16.0
wheel                    0.35.1
zipp                     3.11.0
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 20.2.3; however, version 22.3.1 is available.
You should consider upgrading via the 'C:\Python38\python.exe -m pip install --upgrade pip' command.

In [4]:
import pandas as pd

df = pd.read_csv("melb_data.csv")
df.describe() # Use describe function to get overview of dataset 

# Count shows how many rows have values for this field

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [5]:
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [7]:
# Drop n/as with dropna method
df2 = df.dropna(axis=0)
df2.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,6196.000000,6.196000e+03,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000
mean,2.931407,1.068828e+06,9.751097,3101.947708,2.902034,1.576340,1.573596,471.006940,141.568645,1964.081988,-37.807904,144.990201,7435.489509
std,0.971079,6.751564e+05,5.612065,86.421604,0.970055,0.711362,0.929947,897.449881,90.834824,38.105673,0.075850,0.099165,4337.698917
min,1.000000,1.310000e+05,0.000000,3000.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1196.000000,-38.164920,144.542370,389.000000
25%,2.000000,6.200000e+05,5.900000,3044.000000,2.000000,1.000000,1.000000,152.000000,91.000000,1940.000000,-37.855438,144.926198,4383.750000
50%,3.000000,8.800000e+05,9.000000,3081.000000,3.000000,1.000000,1.000000,373.000000,124.000000,1970.000000,-37.802250,144.995800,6567.000000
75%,4.000000,1.325000e+06,12.400000,3147.000000,3.000000,2.000000,2.000000,628.000000,170.000000,2000.000000,-37.758200,145.052700,10175.000000
max,8.000000,9.000000e+06,47.400000,3977.000000,9.000000,8.000000,10.000000,37000.000000,3112.000000,2018.000000,-37.457090,145.526350,21650.000000

In [9]:
# Prediction target is the price

predict_value = df2.Price # Dot notation is case sensitive 
predict_value

1        1035000.0
2        1465000.0
4        1600000.0
6        1876000.0
7        1636000.0
           ...
12205     601000.0
12206    1050000.0
12207     385000.0
12209     560000.0
12212    2450000.0
Name: Price, Length: 6196, dtype: float64

In [10]:
features = ['Rooms', 'Bedroom2', 'Bathroom', 'YearBuilt', 'Landsize']

feature_df = df2[features]
feature_df.head()

   Rooms  Bedroom2  Bathroom  YearBuilt  Landsize
1      2       2.0       1.0     1900.0     156.0
2      3       3.0       2.0     1900.0     134.0
4      4       3.0       1.0     2014.0     120.0
6      3       4.0       2.0     1910.0     245.0
7      2       2.0       1.0     1890.0     256.0

In [24]:
!{sys.executable} -m pip install --user scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.2.0-cp38-cp38-win_amd64.whl (8.2 MB)
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Requirement already satisfied: numpy>=1.17.3 in c:\python38\lib\site-packages (from scikit-learn) (1.24.0)
Collecting joblib>=1.1.1
  Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
Collecting scipy>=1.3.2
  Downloading scipy-1.9.3-cp38-cp38-win_amd64.whl (39.8 MB)
Installing collected packages: threadpoolctl, joblib, scipy, scikit-learn
Successfully installed joblib-1.2.0 scikit-learn-1.2.0 scipy-1.9.3 threadpoolctl-3.1.0

WARNING: You are using pip version 20.2.3; however, version 22.3.1 is available.
You should consider upgrading via the 'C:\Python38\python.exe -m pip install --upgrade pip' command.

In [25]:
from sklearn.tree import DecisionTreeRegressor